// Commands this plugin exposes to the JS side. tauri-plugin's build helper
// uses this list to auto-generate per-command permission files under
// permissions/autogenerated/commands/<cmd>.toml, which the main app's
// capability file references.
//
// Keep the list in lockstep with the #[tauri::command] functions in src/lib.rs.
const COMMANDS: &[&str] = &[
    "play",
    "pause",
    "resume",
    "stop",
    "seek",
    "set_speed",
    "set_volume",
    "set_mute",
    "set_brightness",
    "set_viewport",
    "hide_viewport",
    "raise_viewport",
    "get_tracks",
    "set_audio_track",
    "set_subtitle_track",
    "get_state",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();

    // Point rustc at `src-tauri/binaries/lib/` so libmpv2 can find
    // `libmpv.dll.a` (the import lib shipped in shinchiro's mpv-winbuild
    // tarball). The directory is created by scripts/download-libmpv.ps1.
    #[cfg(target_os = "windows")]
    {
        let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")
            .expect("CARGO_MANIFEST_DIR not set");
        let lib_dir = std::path::Path::new(&manifest_dir)
            .parent()
            .expect("plugin manifest has no parent dir")
            .join("binaries")
            .join("lib");
        println!("cargo:rustc-link-search=native={}", lib_dir.display());
        println!("cargo:rerun-if-changed={}", lib_dir.display());
    }
}
